[versions]
annotations = "24.0.1"
indra = "3.0.1"
shadow = "8.1.1"
jda = "5.0.0-beta.2"
slf4j = "1.7.36"
okhttp = "4.9.3"
findbugs = "3.0.2"
json = "20220320"
junit = "4.13.1"

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }
json = { module = "org.json:json", version.ref = "json" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-crossdoc = { id = "net.kyori.indra.crossdoc", version.ref = "indra" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[bundles]
